=== Tonneltromb/education-examples/src/main/java/com/ymatin/education/xml/DTD/externalDTD.dtd
<!ELEMENT root (child_1 | child_5)*>
<!ELEMENT child_1 (#PCDATA | child_2 | child_3)*>
<!ELEMENT child_2 (child_2_1)>
<!ELEMENT child_3 (#PCDATA)>
<!ELEMENT child_2_1 (#PCDATA)>
<!ELEMENT child_5 (#PCDATA)>
<!ATTLIST child_5 attr (hello | goodbye) #REQUIRED >

=== Tonneltromb/education-examples/src/main/java/com/ymatin/education/xml/externalDTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE root SYSTEM "F:\Projects\education\src\main\java\com\ymatin\education\xml\DTD\externalDTD.dtd">
<root>
    <child_1>
        <child_2>
            <child_2_1>dfgfg</child_2_1>
        </child_2>
        <child_3>dsdfs</child_3>
    </child_1>
    <child_1>
        <child_2>
            <child_2_1>dfgg</child_2_1>
        </child_2>
    </child_1>
    <child_5 attr="goodbye">sasd</child_5>
</root>
